### ISSUE TITLE
Release 1.6.7

### ISSUE THREAD

**Issue by refueledinc** [magepal/magento2-custom-shipping-rate#22]
Can you please release 1.6.7? Composer is only downloading 1.6.6

**Comment by srenon** [comment]
@refueledinc ... done

**Comment by refueledinc** [comment]
@srenon thank you for the quick response!

**Comment by srenon** [comment]
@refueledinc ... Please remember to "star" our extension https://github.com/magepal/magento2-custom-shipping-rate/stargazers
