### ISSUE TITLE
Invalid block issue

### ISSUE THREAD

**Issue by vijikanna** [magepal/magento2-custom-shipping-rate#24]
I installed this module with magento2.4, And it returns below error on clicking store->config->magepal->custom shipping rate

2 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\Core\Block\Adminhtml\System\Config\Composer\Version
Exception #1 (ReflectionException): Class MagePal\Core\Block\Adminhtml\System\Config\Composer\Version does not exist

![image](https://user-images.githubusercontent.com/96241943/151847602-1c85f11d-aa7f-49b3-a5b5-5047f0da08be.png)

**Comment by srenon** [comment]
You need to install our core extension... https://github.com/magepal/magento2-core
