### ISSUE TITLE
Issue in Installing on magento 2.2.0

### ISSUE THREAD

**Issue by rishabhchd19** [magepal/magento2-custom-shipping-rate#3]
The extension was working perfectly till Magento 2.1.9 but not Installing now on Magneto 2.2.0 giving a framework error not satisfiable.
![2017-10-05_21-31-31](https://user-images.githubusercontent.com/30948461/31237458-adaaca26-aa14-11e7-84a9-914768347af9.jpg)

**Comment by srenon** [comment]
@rishabhchd19 ... I'm working on few other issues in 2.2. Will push an update soon

**Comment by rishabhchd19** [comment]
Hi, any update? :)

**Comment by rishabhchd19** [comment]
I installed version 1.3.0 and it is hiding the content of the entire page of Shipping Methods. After Disabling it, the page showing other shipping methods correctly.

**Comment by srenon** [comment]
Can you check your php/magento error log and let me know what the error is?

![image](https://user-images.githubusercontent.com/1415141/31554757-90582b6e-b00c-11e7-975b-3b54d863b827.png)

**Comment by rishabhchd19** [comment]
The previous module was not compatible with 2.2.0 so I uninstalled and update 2.1.9 to 2.2.0 and then installed fresh using composer. Let me check the error and confirm the same. Thanks

**Comment by rishabhchd19** [comment]
![2017-10-13_22-02-41](https://user-images.githubusercontent.com/30948461/31556355-531e9be2-b062-11e7-93d3-971cc165f410.jpg)

**Comment by srenon** [comment]
If you are getting a white screen that means you are getting a fatal PHP error, can you check an tell me what the error is?

Since Magento change from serializing array to JSON the error may be somewhere in https://github.com/magepal/magento2-customshippingrate/blob/master/Helper/Data.php#L19

**Comment by rishabhchd19** [comment]
Yes, it'ds getting white blank screen and I am still looking for the error from the logs.

**Comment by srenon** [comment]
Try https://stackoverflow.com/a/34695164/1191288 (should show the error on the screen)

**Comment by rishabhchd19** [comment]
will work on it and let you confirm on the same.

**Comment by srenon** [comment]
@rishabhchd19 ... is this still an issue?

**Comment by rishabhchd19** [comment]
Hi, I was just about to comment here..but didn't get time to update here. I just tried the above method you said. I didn't get clear from the log. Yes problem is still there. I have found that php version is 7.0.24 installed and any other compone nts that have been updated for 2.2.0 are working perfectly except this one. Right now I have created cart rules and put custom rate there for specific groups. It would be really good if worked on 2.2.0.

**Comment by Willamin** [comment]
I just ran into the shipping methods blank screen problem. The error message that gets logged to `var/log/system.log` upon visiting the shipping methods configuration is 
```
main.CRITICAL: Unable to unserialize value. [] []
```

**Comment by srenon** [comment]
@Willamin ... 

1. Did you upgrade Magento recently?

 2. What version of this extension are you using?

**Comment by Willamin** [comment]
1. Yes, but that was before I installed this extension. Everything worked fine after upgrading Magento.

2. I'm using version 1.3.0 of this extension.

**Comment by Willamin** [comment]
Update: I set the config value (`carriers/customshippingrate/shipping_type`) manually using n98-magerun2 to what I had in development and now everything works fine. It looks like there's a default configuration set in `etc/config.xml`, but that didn't get saved in the database when I installed the module. 
Here's what I set the config value to:
```json
{"_1511907270182_182":{"code":"custom","title":"Shipping","price":"1000.00"}}
```

**Comment by rishabhchd19** [comment]
What can I do in my case? I was getting the same problem but using Php ver 7.0.24 and magento 2.2.1
