### ISSUE TITLE
Create package and shipping label

### ISSUE THREAD

**Issue by LV2Code** [magepal/magento2-custom-shipping-rate#4]
Hi, 

Checked this module and its really awesome, although I have a question if I want to create shipping label and package how should do this using this code.

**Comment by srenon** [comment]
@LV2Code ... Please provide more information on what you are trying to do

**Comment by LV2Code** [comment]
I want to create package at submit shipment page from the products in order, I have tried many things so far without any luck.

If you can share some light on it, it will be really helpful.

Thanks

**Comment by srenon** [comment]
@LV2Code ... Take a look at Magento/Shipping/Model/Carrier/AbstractCarrier.php

Returning true from one of this function should address your issue. Let me know which one and I will add it.

      /**
     * Check if carrier has shipping tracking option available
     *
     * @return bool
     */
    public function isTrackingAvailable()
    {
        return false;
    }

    /**
     * Check if carrier has shipping label option available
     *
     * @return bool
     */
    public function isShippingLabelsAvailable()
    {
        return false;
    }
