### ISSUE TITLE
Ability to sort shipping rates

### ISSUE THREAD

**Issue by ctadlock** [magepal/magento2-custom-shipping-rate#5]
Need to be able to sort the shipping rates. This should either be done in the admin config when defining the rates, or the dropdown on the order page should sort the rates. I think sorting the rates as a part of configuration is the best and most flexible.

![image](https://user-images.githubusercontent.com/1539397/37999983-3f80db6e-31da-11e8-996e-0ea0e41dd326.png)

![image](https://user-images.githubusercontent.com/1539397/37999996-5110e734-31da-11e8-82d8-6fe0a8e6d688.png)

**Comment by srenon** [comment]
@ctadlock ... Please upgrade to the latest version
